# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/client
    steps:
      - checkout
      - node/install:
          install-yarn: true