version: 2.1
orbs:
  node: circleci/node@4.1.0
  
commands:
  nodejs_install:
    steps:
      - node/install:
          install-yarn: true
          node-version: '14.16.1'

  yarn_lint:
    steps:
      - node/install:
          install-yarn: true
      - run:
          command: |
            yarn install
            yarn lint:eslint
            yarn lint:prettier

jobs:
  build:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/client
    steps:
      - checkout
      - nodejs_install
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
