version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/client
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ~/client/node_modules
      - run: yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ~/client/node_modules
      - run: yarn test
      - run: yarn build
