version: 2.1
orbs:
  node: circleci/node@4.7.0
  
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/client
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
